apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "create-new"
  description: "A component that is part of the DevSecOps catalog"
  annotations:
    
    jenkins.io/job-full-name: create-new-org/create-new-job
    

    
    sonarqube.org/project-key: default/create-new
    

    dependencytrack/project-id: ""
    iap/app-info: "1/5f3a6bac-509f-482e-b1fd-e06f546f71bf"
    backstage.io/techdocs-ref: dir:.

spec:
  type: service
  owner: user:guest
  lifecycle: experimental
